version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16-bullseye
    environment:
      PIHELPER_PIHOLE_HOST: 'http://pihole'
      PIHELPER_API_KEY: 5536c470d038c11793b535e8c1176817c001d6f20a4704fa7908939be82e2922
    volumes:
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"  
    network_mode: service:pihole
    user: node
  pihole:
    image: pihole/pihole
    environment:
      WEBPASSWORD: pihole
    restart: unless-stopped
